# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testMyFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Crypt', :path => "../Crypt/"

  # Pods for testMyFramework

end
